#!/bin/sh
# codegen-gates.sh reports what the compiler did with the hot packages, and
# compares it against a committed golden file.
#
# Three properties this repository argues for at length in comments and did not
# measure until W23:
#
#   bce     bounds checks that survived. execute.go explains twice why a helper
#           takes s rather than a length, and nothing asserted the result.
#   inline  whether a named function is inlinable, and its cost when it is not.
#           parseFracSec carries a table of three rejected implementations, one
#           of which lost on "inline lost in both executors". That was prose.
#
#           A cost here is not always a defect. goLayoutFor is over budget and
#           is meant to be: it is the cold half of a pair, and the hot half,
#           spelledCanonically, is the entry that has to stay inlined. Watching
#           both is what says which is which.
#   escape  values that reached the heap. coverGaps explains why its array must
#           not, which is the allocation the function exists to remove.
#
# The gate is that a number did not GROW, not that the file is identical. An
# improvement is reported and passes, so a change that removes a bounds check
# does not fail CI until somebody regenerates; regenerating is then a deliberate
# commit, the way benchmarks/baseline.txt is.
#
# Every number here is architecture-independent: inline cost is computed from
# the IR before lowering, and the bounds-check and escape passes run on generic
# SSA. Verified by generating this report under GOARCH=arm64 and GOARCH=amd64
# and diffing, which matters because CI runs amd64 and a developer may not.
set -eu

GOLDEN=testdata/codegen/gates.txt
PKGS=". ./internal/compile ./internal/detect"

# INLINE_WATCH is the list this gate has an opinion about. It is not every
# function: the point is to notice a regression on the hot path, not to freeze
# the compiler's output everywhere. A name here is one that a comment in the
# source makes a claim about, or one the executors call per field per parse.
INLINE_WATCH='parse2Digits parse4Digits parse2Bounded parse1or2Bounded numericW
litAccepts sepOK applyAMPM consumed1or2 parseFracSec NormalizeTwoDigitYear
isLeap dayExists lookupTZByOffset fastSlot fusesSeparator spelledCanonically
goLayoutFor respellLiterals internedLayout makeTime daysFromCivil Scan'

report() {
	printf '# generated by scripts/codegen-gates.sh; do not edit by hand\n'
	printf '# toolchain %s (numbers are architecture-independent; see the script)\n' "$(go version | awk '{print $3}')"
	printf '\n[bce] bounds checks that survived, per file\n'
	go build -gcflags='-d=ssa/check_bce/debug=1' $PKGS 2>&1 \
		| grep -E '^(\./|internal/)' \
		| grep -oE '^[a-zA-Z./_]+\.go' \
		| sort | uniq -c | awk '{printf "bce:%s %s\n", $2, $1}'

	printf '\n[inline] watched functions: inlined, or the cost that stopped them\n'
	m2=$(go build -gcflags='-m=2' $PKGS 2>&1 || true)
	for fn in $INLINE_WATCH; do
		if printf '%s\n' "$m2" | grep -qE "can inline $fn( with cost|\$)"; then
			printf 'inline:%s inlined\n' "$fn"
		else
			cost=$(printf '%s\n' "$m2" | sed -n "s/.*cannot inline $fn: function too complex: cost \([0-9]*\) exceeds budget \([0-9]*\).*/\1/p" | head -1)
			if [ -n "$cost" ]; then
				printf 'inline:%s cost=%s\n' "$fn" "$cost"
			else
				printf 'inline:%s not-inlined\n' "$fn"
			fi
		fi
	done | sort

	printf '\n[escape] values that reached the heap, per file\n'
	go build -gcflags='-m' $PKGS 2>&1 \
		| grep -E 'escapes to heap|moved to heap' \
		| grep -E '^(\./|internal/)' \
		| grep -oE '^[a-zA-Z./_]+\.go' \
		| sort | uniq -c | awk '{printf "escape:%s %s\n", $2, $1}'
}

case "${1:-check}" in
update)
	report > "$GOLDEN"
	echo "==> wrote $GOLDEN"
	;;
check)
	if [ ! -f "$GOLDEN" ]; then
		echo "FAIL: $GOLDEN is missing; run 'make codegen-update'" >&2
		exit 1
	fi
	now=$(mktemp); trap 'rm -f "$now"' EXIT
	report > "$now"

	want_tc=$(sed -n 's/^# toolchain \([^ ]*\).*/\1/p' "$GOLDEN")
	have_tc=$(go version | awk '{print $3}')
	if [ "$(echo "$want_tc" | cut -d. -f1,2)" != "$(echo "$have_tc" | cut -d. -f1,2)" ]; then
		echo "FAIL: golden is $want_tc, this toolchain is $have_tc" >&2
		echo "      inline costs move between Go versions; the two have to match" >&2
		exit 1
	fi

	# Compare every "name number" line. Growth fails, a shrink is reported.
	rc=0
	improved=0
	while read -r key val; do
		case "$key" in ''|'#'*|'['*) continue ;; esac
		new=$(awk -v k="$key" '$1==k {print $2}' "$now" | head -1)
		if [ -z "$new" ]; then
			echo "FAIL: $key is in the golden and not in this build" >&2
			rc=1
			continue
		fi
		wn=${val#cost=}; nn=${new#cost=}
		if [ "$val" = inlined ] && [ "$new" != inlined ]; then
			echo "FAIL: $key was inlined and is now $new" >&2
			rc=1
		elif [ "$val" != inlined ] && [ "$new" = inlined ]; then
			echo "  improved: $key is inlined now (was $val)"
			improved=1
		elif [ "$wn" != "$val" ] || [ "$nn" != "$new" ]; then
			# both are cost=N
			if [ "$nn" -gt "$wn" ]; then
				echo "FAIL: $key cost $nn, golden says $wn" >&2
				rc=1
			elif [ "$nn" -lt "$wn" ]; then
				echo "  improved: $key cost $nn, golden says $wn"
				improved=1
			fi
		elif [ "$new" -gt "$val" ] 2>/dev/null; then
			echo "FAIL: $key is $new, golden says $val" >&2
			rc=1
		elif [ "$new" -lt "$val" ] 2>/dev/null; then
			echo "  improved: $key is $new, golden says $val"
			improved=1
		fi
	done < "$GOLDEN"

	# A file or function that appears and is not in the golden is new work
	# nobody has looked at, so it is reported rather than ignored.
	while read -r key val; do
		case "$key" in ''|'#'*|'['*) continue ;; esac
		if ! awk -v k="$key" '$1==k {found=1} END {exit !found}' "$GOLDEN"; then
			echo "FAIL: $key ($val) is new and not in the golden" >&2
			rc=1
		fi
	done < "$now"

	if [ "$rc" -ne 0 ]; then
		echo "" >&2
		echo "A number grew. Either the change made codegen worse, or the new" >&2
		echo "number is correct and 'make codegen-update' should record it in a" >&2
		echo "commit that says why." >&2
		exit 1
	fi
	if [ "$improved" -eq 1 ]; then
		echo "==> codegen gates pass, with improvements above; 'make codegen-update' to record them"
	else
		echo "==> codegen gates pass"
	fi
	;;
*)
	echo "usage: $0 [check|update]" >&2
	exit 2
	;;
esac
